/* stm32f4xx_hal_conf.h — HAL module selection for this demo */
#pragma once

#define HAL_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_CORTEX_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED
#define HAL_PWR_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED

#define HSE_VALUE       8000000U
#define HSE_STARTUP_TIMEOUT 100U
#define HSI_VALUE       16000000U
#define LSI_VALUE       32000U
#define LSE_VALUE       32768U

#define TICK_INT_PRIORITY  0x0FU
#define PREFETCH_ENABLE    1U
#define INSTRUCTION_CACHE_ENABLE 1U
#define DATA_CACHE_ENABLE  1U
